#Upon close of PR delete images from ghcr.io registry‚
#only for PRs originating inside the repo, for others 
#we do not have token (which in turn also implies images
#have not been created)
name: clean_images

on: 
  pull_request:
    types: [closed]
 
env:
  REGISTRY: ghcr.io
  VALSERVER_NAME: ${{ github.repository }}/kuksa-val
  CLIENT_NAME: ${{ github.repository }}/kuksa-client


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:    
    - name: Delete ephemereal kuksa-val images from registry
      uses: bots-house/ghcr-delete-image-action@v1.0.0
      continue-on-error: true
      with:
         owner: eclipse
         name: ${{env.VALSERVER_NAME}
         token: ${{ secrets.PUSH_CONTAINER_TOKEN }}
         tag: pr-${{github.event.pull_request.number}}

    - name: Delete ephemereal kuksa-client images from registry
      uses: bots-house/ghcr-delete-image-action@v1.0.0
      continue-on-error: true
      with:
         owner: eclipse
         name: ${{env.CLIENT_NAME}
         token: ${{ secrets.PUSH_CONTAINER_TOKEN }}
         tag: pr-${{github.event.pull_request.number}}
         
    - name: Finish
      run: echo "Done"
         